@startuml

System_Boundary(c1, "Internet Banking System"){
  Container(web_app, "Web Application", "Java, Spring MVC", "Delivers the static content and the Internet banking SPA")

  Container(spa, "Single-Page App", "JavaScript, Angular", "Provides all the Internet banking functionality to customers via their web browser")

  Container(mobile_app, "Mobile App", "C#, Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device")

  ContainerDb(database, "Database", "SQL Database", "Stores user registration information, hashed auth credentials, access logs, etc.")

  Container(backend_api, "API Application", "Java, Docker Container", "Provides Internet banking functionality via API")
}

@enduml